dataset:
  kitti_odometry_path: "..\\CV Project\\Dataset"
  use_odometry_for_stereo: true
  stereo_sequences: [0, 1, 2, 3, 4, 5]
  vo_sequences: [6, 7, 8, 9, 10]

stereo:
  method: block_matching   # options: sgbm, block_matching
  window_size: 7
  max_disparity: 64
  cost_function: "SSD" # Options: "SAD", "SSD", "NCC"
  consistency_threshold: 3
  median_filter_size: 5

vo:
  feature_detector: "ORB" # Options: "ORB", "SIFT"
  descriptor_type: "ORB" 
  ransac_threshold: 1.0
  ransac_iterations: 1000
  ransac_confidence: 0.99
  min_inliers: 50

output:
  disparity_dir: "outputs/disparity"
  depth_dir: "outputs/depth"
  trajectory_dir: "outputs/trajectory"
  evaluation_dir: "outputs/evaluation"
  visualizations_dir: "outputs/visualizations"